Models/Cart.cs
using Microsoft.AspNetCore.Identity;

namespace Ecommerce.Models
{
    public class Cart
    {
        public int Id { get; set; }

        public int ProductId { get; set; }
        public Product Product { get; set; }
        public int Qty { get; set; }

        public string UserId { get; set; }
        public ApplicationUser User { get; set; }
    }
}

Controllers/CartController.cs
using Ecommerce.Data;
using Ecommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Runtime.InteropServices;

namespace Ecommerce.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        public readonly ApplicationDbContext _context;
        public readonly UserManager<ApplicationUser> _userManager;

        public CartController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var currentuser = await _userManager.GetUserAsync(HttpContext.User);

            var cart = await _context.Carts
                .Include(x => x.Product)
                .Where(x =>x .UserId == currentuser.Id)
                .ToListAsync();

            double totalCost = 0;

            foreach (var cartItem in cart)
            {
                totalCost += cartItem.Product.Price * cartItem.Qty;
            }
         
            ViewBag.TotalCost = totalCost;

            return View(cart);
        }

        public async Task<IActionResult> UpdateQty(int productId, int qty)
        {
            var product = await _context.Products.Where(x => x.Id == productId).FirstOrDefaultAsync();

            if (product == null)
            {
                return BadRequest();
            }

            var currentuser = await _userManager.GetUserAsync(HttpContext.User);

            var cartItem = await _context.Carts.Where(x => x.UserId == currentuser.Id)
                .Where(x =>x .ProductId == productId)
                .FirstOrDefaultAsync();

            if (cartItem == null) { 
                return BadRequest();
            }

            cartItem.Qty = qty;
            _context.Carts.Update(cartItem);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AddToCart(int productId, int qty = 1)
        {

            var currentuser = await _userManager.GetUserAsync(HttpContext.User);

            var product = await _context.Products.Where(x => x.Id == productId).FirstOrDefaultAsync();

            if (product == null)
            {
                return BadRequest();
            }

            var cart = new Cart { ProductId = productId, Qty = qty, UserId = currentuser.Id };

            _context.Add(cart);

            await _context.SaveChangesAsync();

            return RedirectToAction("Index");

        }

        public async Task<IActionResult> Remove(int id)
        {
            var cartItem = await _context.Carts.FindAsync(id);
            if (cartItem == null) {
                return BadRequest();
            }
            _context.Carts.Remove(cartItem);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

Controllers/CheckoutController.cs
using Ecommerce.Configuration;
using Ecommerce.Data;
using Ecommerce.Data.Migrations;
using Ecommerce.Models;
using Ecommerce.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Razorpay.Api;

namespace Ecommerce.Controllers
{
    [Authorize]
    public class CheckoutController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IRazorPayConfiguration _razorPay;

        public CheckoutController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IRazorPayConfiguration razorPay)
        {
            _context = context;
            _userManager = userManager;
            _razorPay = razorPay;
        }


        public async Task<IActionResult> Index()
        {
            var currentuser = await _userManager.GetUserAsync(HttpContext.User);

            var addresses = await _context.Addresses
                .Include(x => x.User)
                .Where(x => x.UserId == currentuser.Id)
                .ToListAsync();

            ViewBag.Addresses = addresses;
            
            return View();
        }

        public async Task<IActionResult> PaymentOptions(int addressId)
        {
            var address = await _context.Addresses.Where(x => x.Id == addressId).FirstOrDefaultAsync();
            if (address == null)
            {
                return BadRequest();
            }

            var currentuser = await _userManager.GetUserAsync(HttpContext.User);

            double orderCost = 0;

            var carts = await _context.Carts
                .Include(x => x.Product)
                .Where(x => x.UserId == currentuser.Id).ToListAsync();

            foreach (var cart in carts)
            {
                orderCost += (cart.Product.Price * cart.Qty);
            }

            var transactionId= Guid.NewGuid().ToString();
            RazorpayClient client = new RazorpayClient(_razorPay.KeyID, _razorPay.KeySecret);

            Dictionary<string, object> options = new Dictionary<string, object>();

            options.Add("amount", orderCost * 100);
            options.Add("receipt", transactionId);
            options.Add("currency", "INR");
            options.Add("payment_capture", "0");

            Razorpay.Api.Order orderResponse= client.Order.Create(options);

            string orderId = orderResponse["id"].ToString();

            var paymentOptions = new PaymentOptions
            {
                addressId = addressId,
                orderId = orderId,
                razorpayKey= _razorPay.KeyID,
                amount= orderCost * 100,
                currency = "INR",
                name = currentuser.FullName,
                email = currentuser.Email,
                contactNumber = currentuser.PhoneNumber,
            };

            ViewBag.items = orderCost;
            ViewBag.tax = 0;
            ViewBag.delivery = 0;
            ViewBag.subtotal = orderCost;
            ViewBag.ordertotal = orderCost;


         

            return View(paymentOptions);
        }


        [HttpPost]
        [AllowAnonymous]
        public async Task<ActionResult> Complete(string rzp_paymentid, string rzp_orderid, int addressId)
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);

            if (user != null)
            {
                var carts = await _context.Carts
                    .Include(x =>x.Product)
                    .Where(x => x.UserId == user.Id).ToListAsync();
               

                // This id is razorpay unique payment id which can be use to get the payment details from razorpay server
                string paymentId = rzp_paymentid;

                // This is orderId
                string orderId = rzp_orderid;

                Razorpay.Api.RazorpayClient client = new Razorpay.Api.RazorpayClient(_razorPay.KeyID, _razorPay.KeySecret);

                Razorpay.Api.Payment payment = client.Payment.Fetch(paymentId);

                // This code is for capture the payment 
                Dictionary<string, object> options = new Dictionary<string, object>();
                options.Add("amount", payment.Attributes["amount"]);
                Razorpay.Api.Payment paymentCaptured = payment.Capture(options);
                string amt = paymentCaptured.Attributes["amount"];
                var amount = double.Parse(amt);
                var order = new Models.Order
                {
                    AddressId = addressId,
                    CreatedAt = DateTime.Now,
                    Status = "Order Placed",
                    UserId = user.Id,
                    Amount = amount/100,
                };

                _context.Orders.Add(order);

                await _context.SaveChangesAsync();

                foreach (var cart in carts)
                {
                    var orderProduct = new OrderProduct
                    {
                        ProductId = cart.ProductId,
                        OrderId = order.Id,
                        Price = cart.Product.Price,
                        Qty = cart.Qty,
                    };
                    _context.Add(orderProduct);
                }

                await _context.SaveChangesAsync();

                _context.RemoveRange(carts);
                await _context.SaveChangesAsync();
            }

           


            return RedirectToAction("ThankYou");

        }

        public IActionResult ThankYou()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(Address address)
        {
            if (ModelState.IsValid)
            {
                var currentuser = await _userManager.GetUserAsync(HttpContext.User);

                address.UserId = currentuser.Id;
                _context.Addresses.Add(address);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View(address);
        }
    }
}

Views/Cart/Index.cshtml
@model List<Cart>

@section PageTitle {
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Shopping Cart</h1>
                <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
            </div>
        </div>
    </header>
}

<section class="bg-light my-5">
    <div class="container">
        <div class="row">
            <!-- cart -->
            <div class="col-lg-9">
                <div class="card border shadow-0">
                    <div class="m-4">
                        <h4 class="card-title mb-4">Your shopping cart</h4>
                     
                        @foreach(var cartItem in Model)
                        {
                            <div class="row gy-3 mb-4">
                                <div class="col-lg-5">
                                    <div class="me-lg-5">
                                        <div class="d-flex">
                                            <img src="@cartItem.Product.Image" class="border rounded me-3" style="width: 96px; height: 96px;">
                                            <div class="">
                                                <a href="#" class="nav-link">@cartItem.Product.Name</a>
                                                @* <p class="text-muted">Yellow, Jeans</p> *@
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-2 col-sm-6 col-6 d-flex flex-row flex-lg-column flex-xl-row text-nowrap">
                                    <div class="">
                                        @{
                                            var selectedValue = cartItem.Qty;

                                            var items = new List<SelectListItem>
                                            {
                                                new SelectListItem { Value = "1", Text = "1", Selected = (selectedValue == 1) },
                                                new SelectListItem { Value = "2", Text = "2", Selected = (selectedValue == 2) },
                                                new SelectListItem { Value = "3", Text = "3", Selected = (selectedValue == 3) },
                                                new SelectListItem { Value = "4", Text = "4", Selected = (selectedValue == 4) },
                                                new SelectListItem { Value = "5", Text = "5", Selected = (selectedValue == 5) },
                                                new SelectListItem { Value = "6", Text = "6", Selected = (selectedValue == 6) },
                                                new SelectListItem { Value = "7", Text = "7", Selected = (selectedValue == 7) },
                                                new SelectListItem { Value = "8", Text = "8", Selected = (selectedValue == 8) },
                                                new SelectListItem { Value = "9", Text = "9", Selected = (selectedValue == 9) },
                                                new SelectListItem { Value = "10", Text = "10", Selected = (selectedValue == 10) },
                                            };
                                        }

                                        <select id="product-@cartItem.ProductId" data-productId="@cartItem.ProductId" style="width: 100px;" class="form-select me-4" onchange="submitCart(@cartItem.ProductId)" asp-items="items">
                                        </select>
                                    </div>
                                    <div class="">
                                        <text class="h6">$@cartItem.Product.Price</text> <br>
                                    </div>
                                </div>
                                <div class="col-lg col-sm-6 d-flex justify-content-sm-center justify-content-md-start justify-content-lg-center justify-content-xl-end mb-2">
                                    <div class="float-md-end">
                                        <a href="#!" class="btn btn-light border px-2 icon-hover-primary"><i class="fas fa-heart fa-lg px-1 text-secondary"></i></a>
                                        <a asp-controller="Cart" asp-action="Remove" asp-route-id="@cartItem.Id" class="btn btn-light border text-danger icon-hover-danger"> Remove</a>
                                    </div>
                                </div>
                            </div>
                        }
          

                    </div>

                    <div class="border-top pt-4 mx-4 mb-4">
                        <p><i class="fas fa-truck text-muted fa-lg"></i> Free Delivery within 1-2 weeks</p>
                        <p class="text-muted">
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                            aliquip
                        </p>
                    </div>
                </div>
            </div>
            <!-- cart -->
            <!-- summary -->
            <div class="col-lg-3">
                <div class="card mb-3 border shadow-0">
                    <div class="card-body">
                        <form>
                            <div class="form-group">
                                <label class="form-label">Have coupon?</label>
                                <div class="input-group">
                                    <input type="text" class="form-control border" name="" placeholder="Coupon code">
                                    <button class="btn btn-light border">Apply</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="card shadow-0 border">
                    <div class="card-body">
                        <div class="d-flex justify-content-between">
                            <p class="mb-2">Total price:</p>
                            <p class="mb-2">$@ViewBag.TotalCost</p>
                        </div>
                     @*    <div class="d-flex justify-content-between">
                            <p class="mb-2">Discount:</p>
                            <p class="mb-2 text-success">-$60.00</p>
                        </div>
                        <div class="d-flex justify-content-between">
                            <p class="mb-2">TAX:</p>
                            <p class="mb-2">$14.00</p>
                        </div> *@
                        <hr>
                        <div class="d-flex justify-content-between">
                            <p class="mb-2">Total price:</p>
                            <p class="mb-2 fw-bold">$@ViewBag.TotalCost</p>
                        </div>

                        <div class="mt-3">
                            <a asp-controller="Checkout" asp-action="Index" class="btn btn-success w-100 shadow-0 mb-2"> Make Purchase </a>
                            <a asp-controller="Home" asp-action="Index" class="btn btn-light w-100 border mt-2"> Back to shop </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- summary -->
        </div>
    </div>
</section>


@section Styles {
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
}

@section Scripts {
    <script>
        function submitCart(productId) {
            // Get the select element for the given product ID
            const selectElement = document.getElementById(`product-${productId}`);

            // Get the selected quantity and the product ID from the data attribute
            const qty = selectElement.value;
            const productID = selectElement.getAttribute('data-productId');

            // Create a new form element
            const form = document.createElement('form');

            form.method = 'GET';
            form.action = '/Cart/UpdateQty';

            // Create hidden input fields for product ID and quantity
            const productInput = document.createElement('input');
            productInput.type = 'hidden';
            productInput.name = 'productId';
            productInput.value = productID;

            const qtyInput = document.createElement('input');
            qtyInput.type = 'hidden';
            qtyInput.name = 'qty';
            qtyInput.value = qty;

            // Append the hidden fields to the form
            form.appendChild(productInput);
            form.appendChild(qtyInput);

            // Append the form to the document body (it's necessary to append before submitting)
            document.body.appendChild(form);

            // Submit the form
            form.submit();
        }
    </script>
}